### ISSUE TITLE
Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by vitorgamer58** [itxtoledo/Stablecoins-Infinity-Profit-Bot#7]
Há um problema na versão em desenvolvimento, eu obtive este erro, ao que parece um problema com a porta 80, temtei desativar meu Firewall UFW mas o erro persistiu.

Segue mais detalhes:
```
Iniciando...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/vitor/StableBot/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/vitor/StableBot/main.js:497:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

npm ERR! Linux 4.15.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! stablecoins-infinity-profit-bot@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stablecoins-infinity-profit-bot@1.0.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the stablecoins-infinity-profit-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs stablecoins-infinity-profit-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls stablecoins-infinity-profit-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vitor/StableBot/npm-debug.log
```

e
```
vitor@vitor-Aspire-5750Z:~/StableBot$ npm version
{ 'stablecoins-infinity-profit-bot': '1.0.0',
  npm: '3.5.2',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

```

Este não é um impeditivo para a minha operação no BOT, pois farei o download do ultimo release, apenas comunicando aqui.

**Comment by arthurcvm** [comment]
Olá, modifique a porta para :3333, ou qualquer outra que não seja a porta web padrão (porta 80), algum software/serviço na sua máquina já deve estar utilizando esta porta (apache por exemplo), por isso entra em conflito e não executa, então opte por outra.

**Comment by vitorgamer58** [comment]
Eu modifiquei para a porta 8082 e deu certo, porém eu obtive outro erro, ele vem depois do inicio do BOT:
```

(node:4918) UnhandledPromiseRejectionWarning: Error: Filter failure: MIN_NOTIONAL
    at /home/vitor/Downloads/StableBot/node_modules/binance-api-node/dist/http-client.js:55:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:4918) UnhandledPromiseRejectionWarning: Error: Filter failure: MIN_NOTIONAL
    at /home/vitor/Downloads/StableBot/node_modules/binance-api-node/dist/http-client.js:55:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```
