### ISSUE TITLE
Error: Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by vitorgamer58** [itxtoledo/Stablecoins-Infinity-Profit-Bot#8]
Bom, agora eu obtive este erro, descrito na Documentação da API da Binace da seguinte forma:

> price * quantity is too low to be a valid order for the symbol.

Segue o erro, aparentemente o BOT tenta colocar uma ordem de compra a uma quantidade abaixo da mínima permitida (10 PAX ou 10 TUSD)

```
===========================================
UPTIME.......: 0.00 horas
ORDENS.......: VENDAS: [ 0 ] COMPRAS: [ 0 ]
DEFINIDOS....: Compra 0.9979 e Venda 1.0009
TIMEOUT ORDEM: 24 horas
HORA AGORA...: Mon Oct 14 2019 20:05:31 GMT-0300 (-03)
============== DADOS DE COMPRA ============
VALOR COMPRA.: 2.53
PRECO COMPRA.: 0.0000
ID ORDEM BUY.: 0
EXPIRA EM....: 1970-01-02T00:00:00.000Z
============== DADOS DE VENDA =============
VALOR VENDA..: 2.53
PRECO VENDA..: 0.0000
ID ORDEM SELL: 0
EXPIRA EM....: 1970-01-02T00:00:00.000Z
===========================================
(node:5253) UnhandledPromiseRejectionWarning: Error: Filter failure: MIN_NOTIONAL
    at /home/vitor/Downloads/StableBot/node_modules/binance-api-node/dist/http-client.js:55:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5253) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5253) UnhandledPromiseRejectionWarning: Error: Filter failure: MIN_NOTIONAL
    at /home/vitor/Downloads/StableBot/node_modules/binance-api-node/dist/http-client.js:55:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by vitorgamer58** [comment]
Resolvido com uma alteração no arquivo de configuração, encontrei o problema em umas linhas de código:

```
total = (marketBalanceLocked + marketBalanceFree + currencyBalanceLocked + currencyBalanceFree + otherStables).toFixed(8);

if((marketBalanceLocked + marketBalanceFree) < (total / 2)) {
	buyAmount =  (((total/2)  * config.BUY_VALUE) / 100 ).toFixed(2);		    
	sellAmount = (((total/2) * config.BUY_VALUE) / 100 ).toFixed(2);
```

A variável de BUY_VALUE estava configurada por padrão em 11 - assim a equação fazia: 
57/2 = 28,50
28,50 * 11 = 313,50
313,50 / 100 = 3,135

sendo assim um valor menor que 10 dólares, ao alterar o valor BUY VALUE para 100 a equação fez-se desta forma:

57/2 = 28,50
28,50 * 100 = 2850
2850 / 100 = 28,50

e então este foi o resultado no LOG:
```
===========================================
SALDO USDT...: 57.444150629999996
SALDO USDS...: 0.09847
OUTRAS STALBE: 0.02362200
SALDO BNB....: 0.00028243
SALDO TOTAL..: 57.56624263 USD
AUTO SPREAD..: ATIVADO
MINIMA DO DIA: 0.9969
MAXIMA DO DIA: 1
USDSUSDT.....: 1
VARIACAO 24H.: 0.13 %
SPREAD 24H...: 0.0031
SPREAD OPERA.: 0.000775
SALDO INICIAL: 57.54262063 USD
LUCRO........: 0.0236 USD
               0.04 %
===========================================
UPTIME.......: 0.01 horas
ORDENS.......: VENDAS: [ 0 ] COMPRAS: [ 1 ]
DEFINIDOS....: Compra 0.9985 e Venda 1.0015
TIMEOUT ORDEM: 24 horas
HORA AGORA...: Thu Oct 17 2019 13:21:01 GMT+0000 (UTC)
============== DADOS DE COMPRA ============
VALOR COMPRA.: 28.78
PRECO COMPRA.: 0.9967
ID ORDEM BUY.: 4670214
EXPIRA EM....: 1970-01-02T00:00:00.000Z
============== DADOS DE VENDA =============
VALOR VENDA..: 28.78
PRECO VENDA..: 0.0000
ID ORDEM SELL: 0
EXPIRA EM....: 1970-01-02T00:00:00.000Z
===========================================

```
